INSERT INTO app_core.sr_algorithms (algorithm_id,
                                    name,
                                    description,
                                    version,
                                    config_schema,
                                    default_config)
VALUES ('sm2',
        'SM-2',
        'Classic SM-2 spaced repetition algorithm',
        '1.0',
        NULL,
        NULL),
       ('fsrs_v5',
        'FSRS v5',
        'Free Spaced Repetition Scheduler v5',
        '5.0',
        NULL,
        NULL),
       ('fsrs_v6',
        'FSRS v6',
        'Free Spaced Repetition Scheduler v6',
        '6.0',
        NULL,
        NULL),
       ('leitner',
        'Leitner',
        'Leitner box scheduling algorithm',
        '1.0',
        NULL,
        NULL),
       ('hlr',
        'HLR',
        'Heuristic long-term retention scheduler',
        '1.0',
        NULL,
        NULL),
       ('afc',
        'AFC',
        'Adaptive forgetting curve algorithm',
        '1.0',
        NULL,
        NULL),
       ('drl',
        'DRL',
        'Deep reinforcement learning scheduler',
        '1.0',
        NULL,
        NULL)
ON CONFLICT (algorithm_id) DO NOTHING;
